@file:Suppress("unused")

package uk.co.alt236.btdeviceinfo.enums

import android.bluetooth.BluetoothClass.Device
import uk.co.alt236.btdeviceinfo.enums.ParsedDeviceMajorClass.AUDIO_VIDEO as MAJOR_AV
import uk.co.alt236.btdeviceinfo.enums.ParsedDeviceMajorClass.COMPUTER as MAJOR_COMPUTER
import uk.co.alt236.btdeviceinfo.enums.ParsedDeviceMajorClass.HEALTH as MAJOR_HEALTH
import uk.co.alt236.btdeviceinfo.enums.ParsedDeviceMajorClass.PERIPHERAL as MAJOR_PERIPHERAL
import uk.co.alt236.btdeviceinfo.enums.ParsedDeviceMajorClass.PHONE as MAJOR_PHONE
import uk.co.alt236.btdeviceinfo.enums.ParsedDeviceMajorClass.TOY as MAJOR_TOY
import uk.co.alt236.btdeviceinfo.enums.ParsedDeviceMajorClass.WEARABLE as MAJOR_WEARABLE

// These are @hidden in Android's BluetoothDevice class
private const val AUDIO_VIDEO_RESERVED_1_ID = 0x040C
private const val AUDIO_VIDEO_RESERVED_2_ID = 0x0444

private const val PERIPHERAL_NON_KEYBOARD_NON_POINTING = 0x0500
private const val PERIPHERAL_KEYBOARD_ID = 0x0540
private const val PERIPHERAL_POINTING_ID = 0x0580
private const val PERIPHERAL_KEYBOARD_POINTING_ID = 0x05C0

enum class ParsedDeviceClass(
    val majorClass: ParsedDeviceMajorClass,
    val androidIdentifier: Int
) {
    UNKNOWN(ParsedDeviceMajorClass.UNKNOWN, -1),

    AUDIO_VIDEO_CAMCORDER(MAJOR_AV, Device.AUDIO_VIDEO_CAMCORDER),
    AUDIO_VIDEO_CAR_AUDIO(MAJOR_AV, Device.AUDIO_VIDEO_CAR_AUDIO),
    AUDIO_VIDEO_HANDSFREE(MAJOR_AV, Device.AUDIO_VIDEO_HANDSFREE),
    AUDIO_VIDEO_HEADPHONES(MAJOR_AV, Device.AUDIO_VIDEO_HEADPHONES),
    AUDIO_VIDEO_HIFI_AUDIO(MAJOR_AV, Device.AUDIO_VIDEO_HIFI_AUDIO),
    AUDIO_VIDEO_LOUDSPEAKER(MAJOR_AV, Device.AUDIO_VIDEO_LOUDSPEAKER),
    AUDIO_VIDEO_MICROPHONE(MAJOR_AV, Device.AUDIO_VIDEO_MICROPHONE),
    AUDIO_VIDEO_PORTABLE_AUDIO(MAJOR_AV, Device.AUDIO_VIDEO_PORTABLE_AUDIO),
    AUDIO_VIDEO_RESERVED_1(MAJOR_AV, AUDIO_VIDEO_RESERVED_1_ID),
    AUDIO_VIDEO_RESERVED_2(MAJOR_AV, AUDIO_VIDEO_RESERVED_2_ID),
    AUDIO_VIDEO_SET_TOP_BOX(MAJOR_AV, Device.AUDIO_VIDEO_SET_TOP_BOX),
    AUDIO_VIDEO_UNCATEGORIZED(MAJOR_AV, Device.AUDIO_VIDEO_UNCATEGORIZED),
    AUDIO_VIDEO_VCR(MAJOR_AV, Device.AUDIO_VIDEO_VCR),
    AUDIO_VIDEO_VIDEO_CAMERA(MAJOR_AV, Device.AUDIO_VIDEO_VIDEO_CAMERA),
    AUDIO_VIDEO_VIDEO_CONFERENCING(MAJOR_AV, Device.AUDIO_VIDEO_VIDEO_CONFERENCING),
    AUDIO_VIDEO_VIDEO_DISPLAY_AND_LOUDSPEAKER(
        MAJOR_AV,
        Device.AUDIO_VIDEO_VIDEO_DISPLAY_AND_LOUDSPEAKER
    ),
    AUDIO_VIDEO_VIDEO_GAMING_TOY(MAJOR_AV, Device.AUDIO_VIDEO_VIDEO_GAMING_TOY),
    AUDIO_VIDEO_VIDEO_MONITOR(MAJOR_AV, Device.AUDIO_VIDEO_VIDEO_MONITOR),
    AUDIO_VIDEO_WEARABLE_HEADSET(MAJOR_AV, Device.AUDIO_VIDEO_WEARABLE_HEADSET),

    COMPUTER_DESKTOP(MAJOR_COMPUTER, Device.COMPUTER_DESKTOP),
    COMPUTER_HANDHELD_PC_PDA(MAJOR_COMPUTER, Device.COMPUTER_HANDHELD_PC_PDA),
    COMPUTER_LAPTOP(MAJOR_COMPUTER, Device.COMPUTER_LAPTOP),
    COMPUTER_PALM_SIZE_PC_PDA(MAJOR_COMPUTER, Device.COMPUTER_PALM_SIZE_PC_PDA),
    COMPUTER_SERVER(MAJOR_COMPUTER, Device.COMPUTER_SERVER),
    COMPUTER_UNCATEGORIZED(MAJOR_COMPUTER, Device.COMPUTER_UNCATEGORIZED),
    COMPUTER_WEARABLE(MAJOR_COMPUTER, Device.COMPUTER_WEARABLE),

    HEALTH_BLOOD_PRESSURE(MAJOR_HEALTH, Device.HEALTH_BLOOD_PRESSURE),
    HEALTH_DATA_DISPLAY(MAJOR_HEALTH, Device.HEALTH_DATA_DISPLAY),
    HEALTH_GLUCOSE(MAJOR_HEALTH, Device.HEALTH_GLUCOSE),
    HEALTH_PULSE_OXIMETER(MAJOR_HEALTH, Device.HEALTH_PULSE_OXIMETER),
    HEALTH_PULSE_RATE(MAJOR_HEALTH, Device.HEALTH_PULSE_RATE),
    HEALTH_THERMOMETER(MAJOR_HEALTH, Device.HEALTH_THERMOMETER),
    HEALTH_UNCATEGORIZED(MAJOR_HEALTH, Device.HEALTH_UNCATEGORIZED),
    HEALTH_WEIGHING(MAJOR_HEALTH, Device.HEALTH_WEIGHING),

    PERIPHERAL_KEYBOARD(MAJOR_PERIPHERAL, PERIPHERAL_KEYBOARD_ID),
    PERIPHERAL_KEYBOARD_POINTING(MAJOR_PERIPHERAL, PERIPHERAL_POINTING_ID),
    PERIPHERAL_POINTING(MAJOR_PERIPHERAL, PERIPHERAL_KEYBOARD_POINTING_ID),
    PERIPHERAL_UNCATEGORIZED(MAJOR_PERIPHERAL, PERIPHERAL_NON_KEYBOARD_NON_POINTING),

    PHONE_CELLULAR(MAJOR_PHONE, Device.PHONE_CELLULAR),
    PHONE_CORDLESS(MAJOR_PHONE, Device.PHONE_CORDLESS),
    PHONE_ISDN(MAJOR_PHONE, Device.PHONE_ISDN),
    PHONE_MODEM_OR_GATEWAY(MAJOR_PHONE, Device.PHONE_MODEM_OR_GATEWAY),
    PHONE_SMART(MAJOR_PHONE, Device.PHONE_SMART),
    PHONE_UNCATEGORIZED(MAJOR_PHONE, Device.PHONE_UNCATEGORIZED),

    TOY_CONTROLLER(MAJOR_TOY, Device.TOY_CONTROLLER),
    TOY_DOLL_ACTION_FIGURE(MAJOR_TOY, Device.TOY_DOLL_ACTION_FIGURE),
    TOY_GAME(MAJOR_TOY, Device.TOY_GAME),
    TOY_ROBOT(MAJOR_TOY, Device.TOY_ROBOT),
    TOY_UNCATEGORIZED(MAJOR_TOY, Device.TOY_UNCATEGORIZED),
    TOY_VEHICLE(MAJOR_TOY, Device.TOY_VEHICLE),

    WEARABLE_GLASSES(MAJOR_WEARABLE, Device.WEARABLE_GLASSES),
    WEARABLE_HELMET(MAJOR_WEARABLE, Device.WEARABLE_HELMET),
    WEARABLE_JACKET(MAJOR_WEARABLE, Device.WEARABLE_JACKET),
    WEARABLE_PAGER(MAJOR_WEARABLE, Device.WEARABLE_PAGER),
    WEARABLE_UNCATEGORIZED(MAJOR_WEARABLE, Device.WEARABLE_UNCATEGORIZED),
    WEARABLE_WRIST_WATCH(MAJOR_WEARABLE, Device.WEARABLE_WRIST_WATCH);

    companion object {
        internal fun fromAndroidIdentifier(identifier: Int): ParsedDeviceClass {
            for (deviceClass in values()) {
                if (identifier == deviceClass.androidIdentifier) {
                    return deviceClass
                }
            }
            return UNKNOWN
        }
    }
}